/**
 * Types for Anthropic streaming events
 *
 * These types represent the structure of events from the Anthropic beta
 * tool runner stream. Since these are beta features, the SDK may not have
 * complete type definitions.
 *
 * @see https://platform.claude.com/docs/en/build-with-claude/extended-thinking
 * @see https://platform.claude.com/docs/en/build-with-claude/effort
 */

// ============================================================================
// Effort Parameter Types
// ============================================================================

/**
 * Effort level for controlling token usage
 *
 * **Note: Only supported by Claude Opus 4.5 (`claude-opus-4-5-20251101`).**
 * This parameter is ignored for Sonnet and other models.
 *
 * - `high`: Maximum capability—Claude uses as many tokens as needed (default)
 * - `medium`: Balanced approach with moderate token savings
 * - `low`: Most efficient—significant token savings with some capability reduction
 *
 * @see https://platform.claude.com/docs/en/build-with-claude/effort
 */
export type EffortLevel = 'low' | 'medium' | 'high'

// ============================================================================
// Extended Thinking Types
// ============================================================================

/**
 * Thinking block from Claude's extended thinking response
 *
 * Contains Claude's step-by-step reasoning process. The signature field
 * is used to verify the thinking block was generated by Claude.
 *
 * @see https://platform.claude.com/docs/en/build-with-claude/extended-thinking
 */
export type ThinkingContentBlock = {
  type: 'thinking'
  thinking: string
  signature: string
}

/**
 * Redacted thinking block when Claude's reasoning triggers safety systems
 *
 * The data field contains encrypted content that can be passed back to the API
 * to maintain reasoning continuity without exposing the actual thinking.
 *
 * @see https://platform.claude.com/docs/en/build-with-claude/extended-thinking#thinking-redaction
 */
export type RedactedThinkingContentBlock = {
  type: 'redacted_thinking'
  data: string
}

// ============================================================================
// Content Block Types
// ============================================================================

export type ToolUseContentBlock = {
  type: 'tool_use'
  id: string
  name: string
  input?: Record<string, unknown>
}

export type ServerToolUseContentBlock = {
  type: 'server_tool_use'
  id: string
  name: string
  input?: Record<string, unknown>
}

export type WebFetchToolResultBlock = {
  type: 'web_fetch_tool_result'
  content: unknown
}

export type WebSearchToolResultBlock = {
  type: 'web_search_tool_result'
  content: unknown[]
}

export type TextContentBlock = {
  type: 'text'
  text: string
}

export type ContentBlock =
  | ThinkingContentBlock
  | RedactedThinkingContentBlock
  | ToolUseContentBlock
  | ServerToolUseContentBlock
  | WebFetchToolResultBlock
  | WebSearchToolResultBlock
  | TextContentBlock
  | { type: string; [key: string]: unknown }

// ============================================================================
// Delta Types
// ============================================================================

export type TextDelta = {
  type: 'text_delta'
  text: string
}

export type ThinkingDelta = {
  type: 'thinking_delta'
  thinking: string
}

export type InputJsonDelta = {
  type: 'input_json_delta'
  partial_json: string
}

export type CitationDelta = {
  citations?: RawCitation[]
}

export type StreamDelta = Partial<TextDelta & ThinkingDelta & InputJsonDelta & CitationDelta> & {
  type?: string
}

// ============================================================================
// Stream Event Types
// ============================================================================

export type ContentBlockStartEvent = {
  type: 'content_block_start'
  index: number
  content_block: ContentBlock
}

export type ContentBlockDeltaEvent = {
  type: 'content_block_delta'
  index: number
  delta: StreamDelta
}

export type ContentBlockStopEvent = {
  type: 'content_block_stop'
  index: number
}

export type MessageStopEvent = {
  type: 'message_stop'
  message?: {
    stop_reason?: 'end_turn' | 'max_tokens' | 'stop_sequence' | 'tool_use' | 'pause_turn'
  }
}

export type MessageStartEvent = {
  type: 'message_start'
  message: {
    id: string
    type: 'message'
    role: 'assistant'
    model: string
  }
}

export type StreamEvent =
  | ContentBlockStartEvent
  | ContentBlockDeltaEvent
  | ContentBlockStopEvent
  | MessageStopEvent
  | MessageStartEvent
  | { type: string; [key: string]: unknown }

// ============================================================================
// Citation Types (for stream processing)
// ============================================================================

export type RawCitation = {
  type: string
  cited_text?: string
  url?: string
  title?: string
  source?: string
  document_index?: number
  document_title?: string
  start_char_index?: number
  end_char_index?: number
  start_page_number?: number
  end_page_number?: number
  start_block_index?: number
  end_block_index?: number
  search_result_index?: number
}

// ============================================================================
// SSE Handler Types
// ============================================================================

export type SSEPayload = {
  choices?: Array<{
    delta: {
      content?: string
      reasoning?: string
      citations?: unknown[]
      pause_turn?: boolean
      tool_use?: unknown
      images?: unknown[]
    }
  }>
  containerId?: string
  error?: {
    message: string
  }
}

